const SET_CURRENT_CITY = "@getWeather/SET_CURRENT_WEATHER"
const GET_WEATHER_FOR_CURRENT_CITY = "@getWeather/GET_WEATHER_FOR_CURRENT_CITY"
const GET_WEATHER_FORECAST_FOR_CURRENT_CITY = "@getWeather/GET_WEATHER_FORECAST_FOR_CURRENT_CITY"
export default {
    SET_CURRENT_CITY,
    GET_WEATHER_FOR_CURRENT_CITY,
    GET_WEATHER_FORECAST_FOR_CURRENT_CITY
}
